# Generated by Django 3.2.3 on 2021-05-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('task_tel', models.CharField(max_length=100)),
                ('ice_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
